export const userList = [
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    phone: "+1234567890",
    website: "johndoe.com",
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    phone: "+1987654321",
    website: "janesmith.com",
  },
  {
    id: 3,
    name: "Michael Johnson",
    email: "mike.j@example.com",
    phone: "+1122334455",
    website: "mikej.com",
  },
  {
    id: 4,
    name: "Emily Brown",
    email: "emily.brown@example.com",
    phone: "+1555098765",
    website: "emilybrown.com",
  },
  {
    id: 5,
    name: "David Wilson",
    email: "david.wilson@example.com",
    phone: "+1789456321",
    website: "davidwilson.com",
  },
  {
    id: 6,
    name: "Sarah Davis",
    email: "sarah.davis@example.com",
    phone: "+1666777888",
    website: "sarahdavis.com",
  },
  {
    id: 7,
    name: "Robert Taylor",
    email: "robert.taylor@example.com",
    phone: "+1888222333",
    website: "rtaylor.com",
  },
  {
    id: 8,
    name: "Olivia Martinez",
    email: "olivia.martinez@example.com",
    phone: "+1999777666",
    website: "oliviamartinez.com",
  },
  {
    id: 9,
    name: "James Anderson",
    email: "james.anderson@example.com",
    phone: "+1444555666",
    website: "jamesanderson.com",
  },
  {
    id: 10,
    name: "Sophia Garcia",
    email: "sophia.garcia@example.com",
    phone: "+1222333444",
    website: "sophiagarcia.com",
  },
  {
    id: 11,
    name: "Daniel Thomas",
    email: "daniel.thomas@example.com",
    phone: "+1333444555",
    website: "danielthomas.com",
  },
  {
    id: 12,
    name: "Isabella Lopez",
    email: "isabella.lopez@example.com",
    phone: "+1555666777",
    website: "isabellalopez.com",
  },
  {
    id: 13,
    name: "Liam Hernandez",
    email: "liam.hernandez@example.com",
    phone: "+1777888999",
    website: "liamhernandez.com",
  },
  {
    id: 14,
    name: "Ava Martinez",
    email: "ava.martinez@example.com",
    phone: "+1888999111",
    website: "avamartinez.com",
  },
  {
    id: 15,
    name: "Ethan Robinson",
    email: "ethan.robinson@example.com",
    phone: "+1666111222",
    website: "ethanrobinson.com",
  },
];
