export interface IRestList {
  id: string;
  resName: string;
  cuisine: string;
  rating: number;
  cost: number;
  time: number;
  image?: string;
}

export const restList: IRestList[] = [
  {
    id: "r1",
    resName: "Burger King",
    cuisine: "Chinese",
    rating: 4.5,
    cost: 500,
    time: 38,
    image: "food1.jpg",
  },
  {
    id: "r2",
    resName: "Pizza Hut",
    cuisine: "Italian",
    rating: 4.2,
    cost: 600,
    time: 45,
    image: "food2.jpg",
  },
  {
    id: "r3",
    resName: "Taco Bell",
    cuisine: "Mexican",
    rating: 4.0,
    cost: 450,
    time: 30,
    image: "food2.jpg",
  },
  {
    id: "r4",
    resName: "Sushi Palace",
    cuisine: "Japanese",
    rating: 4.7,
    cost: 800,
    time: 50,
    image: "food1.jpg",
  },
  {
    id: "r5",
    resName: "Pasta Place",
    cuisine: "Italian",
    rating: 4.3,
    cost: 550,
    time: 40,
    image: "food1.jpg",
  },
  {
    id: "r6",
    resName: "Curry House",
    cuisine: "Indian",
    rating: 4.6,
    cost: 700,
    time: 55,
    image: "food1.jpg",
  },
  {
    id: "r7",
    resName: "BBQ Joint",
    cuisine: "American",
    rating: 4.4,
    cost: 650,
    time: 48,
    image: "food1.jpg",
  },
  {
    id: "r8",
    resName: "Pho Corner",
    cuisine: "Vietnamese",
    rating: 4.1,
    cost: 500,
    time: 35,
    image: "food1.jpg",
  },
  {
    id: "r9",
    resName: "Falafel Stop",
    cuisine: "Middle Eastern",
    rating: 4.3,
    cost: 480,
    time: 32,
    image: "food1.jpg",
  },
  {
    id: "r10",
    resName: "Bistro 34",
    cuisine: "French",
    rating: 4.8,
    cost: 900,
    time: 60,
    image: "food1.jpg",
  },
  {
    id: "r11",
    resName: "Ramen Bar",
    cuisine: "Japanese",
    rating: 4.6,
    cost: 750,
    time: 52,
    image: "food1.jpg",
  },
  {
    id: "r12",
    resName: "Mediterranean Grill",
    cuisine: "Mediterranean",
    rating: 4.2,
    cost: 580,
    time: 42,
    image: "food1.jpg",
  },
  {
    id: "r13",
    resName: "Diner's Delight",
    cuisine: "American",
    rating: 4.0,
    cost: 500,
    time: 37,
    image: "food1.jpg",
  },
  {
    id: "r14",
    resName: "Thai Terrace",
    cuisine: "Thai",
    rating: 4.5,
    cost: 620,
    time: 47,
    image: "food1.jpg",
  },
  {
    id: "r15",
    resName: "Fish n' Chips",
    cuisine: "British",
    rating: 4.3,
    cost: 540,
    time: 39,
    image: "food1.jpg",
  },
  {
    id: "r16",
    resName: "Tandoori Palace",
    cuisine: "Indian",
    rating: 4.7,
    cost: 780,
    time: 58,
    image: "food1.jpg",
  },
  {
    id: "r17",
    resName: "Sushi Express",
    cuisine: "Japanese",
    rating: 4.4,
    cost: 680,
    time: 46,
    image: "food1.jpg",
  },
  {
    id: "r18",
    resName: "Burrito Haven",
    cuisine: "Mexican",
    rating: 4.2,
    cost: 520,
    time: 36,
    image: "food1.jpg",
  },
  {
    id: "r19",
    resName: "Gourmet Grill",
    cuisine: "American",
    rating: 4.6,
    cost: 700,
    time: 53,
    image: "food1.jpg",
  },
  {
    id: "r20",
    resName: "Pizzeria Romano",
    cuisine: "Italian",
    rating: 4.9,
    cost: 950,
    time: 65,
    image: "food1.jpg",
  },
];

export interface IMenuItem {
  itemName: string;
  price: number;
}

export interface IRestMenu {
  id: string;
  resName: string;
  menu: IMenuItem[];
}

export const restMenu: IRestMenu[] = [
  {
    id: "r1",
    resName: "Burger King",
    menu: [
      { itemName: "Burger", price: 500 },
      { itemName: "Fries", price: 150 },
      { itemName: "Milkshake", price: 200 },
      { itemName: "Chicken Nuggets", price: 300 },
      { itemName: "Onion Rings", price: 180 },
      { itemName: "Soft Drink", price: 100 },
      { itemName: "Cheeseburger", price: 550 },
      { itemName: "Ice Cream Sundae", price: 250 },
      { itemName: "Salad", price: 200 },
    ],
  },
  {
    id: "r2",
    resName: "Pizza Hut",
    menu: [
      { itemName: "Margherita Pizza", price: 600 },
      { itemName: "Pepperoni Pizza", price: 650 },
      { itemName: "Garlic Breadsticks", price: 200 },
      { itemName: "Calzone", price: 700 },
      { itemName: "Chicken Wings", price: 450 },
      { itemName: "Pasta Alfredo", price: 550 },
      { itemName: "Caesar Salad", price: 300 },
      { itemName: "Tiramisu", price: 350 },
      { itemName: "Soft Drinks", price: 150 },
    ],
  },
  {
    id: "r3",
    resName: "Taco Bell",
    menu: [
      { itemName: "Crunchy Taco", price: 450 },
      { itemName: "Burrito Supreme", price: 550 },
      { itemName: "Nachos BellGrande", price: 400 },
      { itemName: "Quesadilla", price: 350 },
      { itemName: "Mexican Pizza", price: 600 },
      { itemName: "Churros", price: 250 },
      { itemName: "Guacamole", price: 200 },
      { itemName: "Soft Taco", price: 300 },
      { itemName: "Mexican Rice", price: 180 },
    ],
  },
  {
    id: "r4",
    resName: "Sushi Palace",
    menu: [
      { itemName: "Sushi Platter", price: 800 },
      { itemName: "Sashimi Deluxe", price: 900 },
      { itemName: "Miso Soup", price: 150 },
      { itemName: "Tempura", price: 700 },
      { itemName: "Edamame", price: 250 },
      { itemName: "Tuna Roll", price: 600 },
      { itemName: "Salmon Nigiri", price: 450 },
      { itemName: "Vegetable Tempura", price: 300 },
      { itemName: "Green Tea Ice Cream", price: 200 },
    ],
  },
  {
    id: "r5",
    resName: "Pasta Place",
    menu: [
      { itemName: "Spaghetti Carbonara", price: 550 },
      { itemName: "Lasagna", price: 600 },
      { itemName: "Garlic Bread", price: 200 },
      { itemName: "Ravioli", price: 650 },
      { itemName: "Pesto Pasta", price: 500 },
      { itemName: "Caprese Salad", price: 300 },
      { itemName: "Minestrone Soup", price: 180 },
      { itemName: "Tiramisu", price: 350 },
      { itemName: "Limoncello", price: 250 },
    ],
  },
  {
    id: "r6",
    resName: "Curry House",
    menu: [
      { itemName: "Chicken Tikka Masala", price: 700 },
      { itemName: "Lamb Curry", price: 750 },
      { itemName: "Vegetable Biryani", price: 600 },
      { itemName: "Naan Bread", price: 200 },
      { itemName: "Pakora", price: 400 },
      { itemName: "Samosa", price: 300 },
      { itemName: "Mango Lassi", price: 250 },
      { itemName: "Gulab Jamun", price: 180 },
      { itemName: "Papadum", price: 150 },
    ],
  },
  {
    id: "r7",
    resName: "BBQ Joint",
    menu: [
      { itemName: "BBQ Ribs", price: 650 },
      { itemName: "Pulled Pork Sandwich", price: 600 },
      { itemName: "Coleslaw", price: 150 },
      { itemName: "Brisket", price: 700 },
      { itemName: "Cornbread", price: 250 },
      { itemName: "Mac and Cheese", price: 300 },
      { itemName: "Sweet Potato Fries", price: 200 },
      { itemName: "Banana Pudding", price: 350 },
      { itemName: "BBQ Chicken", price: 550 },
    ],
  },
  {
    id: "r8",
    resName: "Pho Corner",
    menu: [
      { itemName: "Beef Pho", price: 500 },
      { itemName: "Spring Rolls", price: 250 },
      { itemName: "Vietnamese Iced Coffee", price: 200 },
      { itemName: "Banh Mi", price: 300 },
      { itemName: "Shrimp Pho", price: 550 },
      { itemName: "Vegetarian Pho", price: 450 },
      { itemName: "Pork Belly Bao", price: 350 },
      { itemName: "Fried Tofu", price: 180 },
      { itemName: "Che Ba Mau", price: 250 },
    ],
  },
  {
    id: "r9",
    resName: "Falafel Stop",
    menu: [
      { itemName: "Falafel Wrap", price: 480 },
      { itemName: "Hummus Plate", price: 300 },
      { itemName: "Tabouleh Salad", price: 250 },
      { itemName: "Baba Ghanoush", price: 350 },
      { itemName: "Stuffed Grape Leaves", price: 400 },
      { itemName: "Israeli Salad", price: 200 },
      { itemName: "Pita Chips", price: 150 },
      { itemName: "Baklava", price: 180 },
      { itemName: "Turkish Coffee", price: 100 },
    ],
  },
  {
    id: "r10",
    resName: "Bistro 34",
    menu: [
      { itemName: "Filet Mignon", price: 900 },
      { itemName: "Escargot", price: 800 },
      { itemName: "Creme Brulee", price: 300 },
      { itemName: "Foie Gras", price: 1200 },
      { itemName: "Truffle Risotto", price: 1000 },
      { itemName: "Charcuterie Board", price: 700 },
      { itemName: "Lobster Bisque", price: 500 },
      { itemName: "Oysters Rockefeller", price: 600 },
      { itemName: "Champagne", price: 250 },
    ],
  },
  {
    id: "r11",
    resName: "Ramen Bar",
    menu: [
      { itemName: "Tonkotsu Ramen", price: 750 },
      { itemName: "Miso Ramen", price: 700 },
      { itemName: "Gyoza", price: 250 },
      { itemName: "Karaage Chicken", price: 400 },
      { itemName: "Sushi Roll", price: 600 },
      { itemName: "Matcha Ice Cream", price: 300 },
      { itemName: "Seaweed Salad", price: 200 },
      { itemName: "Sake", price: 350 },
      { itemName: "Shochu", price: 180 },
    ],
  },
  {
    id: "r12",
    resName: "Mediterranean Grill",
    menu: [
      { itemName: "Shawarma Plate", price: 580 },
      { itemName: "Hummus and Pita", price: 300 },
      { itemName: "Greek Salad", price: 250 },
      { itemName: "Baklava", price: 200 },
      { itemName: "Spanakopita", price: 400 },
      { itemName: "Feta Cheese Dip", price: 180 },
      { itemName: "Stuffed Grape Leaves", price: 350 },
      { itemName: "Lentil Soup", price: 150 },
      { itemName: "Mint Tea", price: 100 },
    ],
  },
  {
    id: "r13",
    resName: "Diner's Delight",
    menu: [
      { itemName: "Cheeseburger", price: 500 },
      { itemName: "Milkshake", price: 300 },
      { itemName: "Onion Rings", price: 200 },
      { itemName: "BLT Sandwich", price: 450 },
      { itemName: "Pancakes", price: 350 },
      { itemName: "French Toast", price: 280 },
      { itemName: "Grilled Cheese", price: 250 },
      { itemName: "Chicken Salad", price: 320 },
      { itemName: "Apple Pie", price: 180 },
    ],
  },
  {
    id: "r14",
    resName: "Thai Terrace",
    menu: [
      { itemName: "Pad Thai", price: 620 },
      { itemName: "Green Curry", price: 600 },
      { itemName: "Thai Iced Tea", price: 200 },
      { itemName: "Tom Yum Soup", price: 450 },
      { itemName: "Papaya Salad", price: 300 },
      { itemName: "Massaman Curry", price: 550 },
      { itemName: "Mango Sticky Rice", price: 250 },
      { itemName: "Fish Cakes", price: 180 },
      { itemName: "Coconut Ice Cream", price: 200 },
    ],
  },
  {
    id: "r15",
    resName: "Fish n' Chips",
    menu: [
      { itemName: "Fish and Chips", price: 540 },
      { itemName: "Mushy Peas", price: 150 },
      { itemName: "Tartar Sauce", price: 100 },
      { itemName: "Scotch Egg", price: 200 },
      { itemName: "Seafood Platter", price: 650 },
      { itemName: "Smoked Haddock", price: 400 },
      { itemName: "Battered Sausage", price: 180 },
      { itemName: "Whitebait", price: 250 },
      { itemName: "Fruit Salad", price: 120 },
    ],
  },
  {
    id: "r16",
    resName: "Tandoori Palace",
    menu: [
      { itemName: "Chicken Tikka", price: 780 },
      { itemName: "Paneer Tikka", price: 700 },
      { itemName: "Naan Bread", price: 200 },
      { itemName: "Tandoori Mixed Grill", price: 850 },
      { itemName: "Saag Paneer", price: 600 },
      { itemName: "Aloo Gobi", price: 500 },
      { itemName: "Mango Lassi", price: 250 },
      { itemName: "Papad", price: 100 },
      { itemName: "Kheer", price: 180 },
    ],
  },
  {
    id: "r17",
    resName: "Sushi Express",
    menu: [
      { itemName: "California Roll", price: 680 },
      { itemName: "Tempura", price: 600 },
      { itemName: "Edamame", price: 250 },
      { itemName: "Tuna Tataki", price: 750 },
      { itemName: "Spider Roll", price: 700 },
      { itemName: "Salmon Sashimi", price: 500 },
      { itemName: "Yellowtail Nigiri", price: 400 },
      { itemName: "Seaweed Salad", price: 180 },
      { itemName: "Sake", price: 300 },
    ],
  },
  {
    id: "r18",
    resName: "Burrito Haven",
    menu: [
      { itemName: "Burrito", price: 520 },
      { itemName: "Guacamole", price: 200 },
      { itemName: "Chips and Salsa", price: 150 },
      { itemName: "Enchiladas", price: 600 },
      { itemName: "Tacos", price: 450 },
      { itemName: "Mexican Rice", price: 180 },
      { itemName: "Churros", price: 250 },
      { itemName: "Horchata", price: 200 },
      { itemName: "Tres Leches", price: 350 },
    ],
  },
  {
    id: "r19",
    resName: "Gourmet Grill",
    menu: [
      { itemName: "Ribeye Steak", price: 700 },
      { itemName: "Caesar Salad", price: 300 },
      { itemName: "Garlic Mashed Potatoes", price: 250 },
      { itemName: "Grilled Salmon", price: 600 },
      { itemName: "Crab Cakes", price: 650 },
      { itemName: "Lobster Tail", price: 900 },
      { itemName: "Asparagus Soup", price: 200 },
      { itemName: "Chocolate Fondue", price: 400 },
      { itemName: "Red Wine", price: 180 },
    ],
  },
  {
    id: "r20",
    resName: "Pizzeria Romano",
    menu: [
      { itemName: "Quattro Stagioni Pizza", price: 950 },
      { itemName: "Capricciosa Pizza", price: 900 },
      { itemName: "Tiramisu", price: 350 },
      { itemName: "Antipasto Platter", price: 700 },
      { itemName: "Bruschetta", price: 300 },
      { itemName: "Italian Wedding Soup", price: 250 },
      { itemName: "Prosciutto", price: 180 },
      { itemName: "Limoncello", price: 200 },
      { itemName: "Espresso", price: 100 },
    ],
  },
];
